POST http://localhost:3001/api/products
Content-Type: application/json

{
  "barsCode": 2410210421,
  "name": "Product 3",
  "creationDate": "Mon Apr 19 2021 19:24:35 GMT-0500 (Colombia Standard Time)",
  "description": "Description Product 3",
  "price": 34
}